class Wisata {
  final String nomer;
  final String imageUrl;
  final String title;
  final String lokasi;
  final String rate;
  final String link;
  const Wisata(
      {required this.nomer,
      required this.imageUrl,
      required this.title,
      required this.lokasi,
      required this.rate,
      required this.link});
}

const allWisata = [
  Wisata(
      nomer: "1.  ",
      imageUrl: "images/pgununggeder.jpg",
      title: "Tarogong Kidul",
      lokasi: "20 Destinasi Wisata",
      rate: "55",
      link: "WisataKecamatan"),
  Wisata(
      nomer: "2.  ",
      imageUrl: "images/image 19.png",
      title: "Tarogong Kaler",
      lokasi: "15 Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "3.  ",
      imageUrl: "images/pgununggeder.jpg",
      title: "Samarang ",
      lokasi: "10 Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "4.  ",
      imageUrl: "images/image 19.png",
      title: "Garut Kota",
      lokasi: "14Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "5.  ",
      imageUrl: "images/image 19.png",
      title: "Kadungora",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "6.  ",
      imageUrl: "images/image 19.png",
      title: "Leles",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "7.  ",
      imageUrl: "images/image 19.png",
      title: "Wanaraja",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "8.  ",
      imageUrl: "images/image 19.png",
      title: "Cilawu",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "9.  ",
      imageUrl: "images/image 19.png",
      title: "Darajat",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "10  ",
      imageUrl: "images/image 19.png",
      title: " Banjarwangi",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "2.  ",
      imageUrl: "images/image 19.png",
      title: "Banyuresmi",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "3.  ",
      imageUrl: "images/image 19.png",
      title: "Bayongbong ",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "4.  ",
      imageUrl: "images/image 19.png",
      title: "Limbangan",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "5.  ",
      imageUrl: "images/image 19.png",
      title: "Bungbulang",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "6.  ",
      imageUrl: "images/image 19.png",
      title: "Caringin",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "7.  ",
      imageUrl: "images/image 19.png",
      title: "Cibalong",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "8.  ",
      imageUrl: "images/image 19.png",
      title: "Cibatu",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "9.  ",
      imageUrl: "images/image 19.png",
      title: "Cibiuk",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "1.  ",
      imageUrl: "images/image 19.png",
      title: "Cigedug",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "2.  ",
      imageUrl: "images/image 19.png",
      title: "Cihurip",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "3.  ",
      imageUrl: "images/image 19.png",
      title: "	Cikajang ",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "4.  ",
      imageUrl: "images/image 19.png",
      title: "Cikelet",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "5.  ",
      imageUrl: "images/image 19.png",
      title: "Cisewu",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "6.  ",
      imageUrl: "images/image 19.png",
      title: "Cisompet",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "7.  ",
      imageUrl: "images/image 19.png",
      title: "Cisurupan",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "8.  ",
      imageUrl: "images/image 19.png",
      title: "Karangpawitan",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "9.  ",
      imageUrl: "images/image 19.png",
      title: "Karangtengah",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "1.  ",
      imageUrl: "images/image 19.png",
      title: "Kersamanah",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "2.  ",
      imageUrl: "images/image 19.png",
      title: "Leuwigoong",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "3.  ",
      imageUrl: "images/image 19.png",
      title: "Malangbong ",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "4.  ",
      imageUrl: "images/image 19.png",
      title: "Mekarmukti",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "5.  ",
      imageUrl: "images/image 19.png",
      title: "Pakenjeng",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "6.  ",
      imageUrl: "images/image 19.png",
      title: "Pameungpeuk",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "7.  ",
      imageUrl: "images/image 19.png",
      title: "Pamulihan",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "8.  ",
      imageUrl: "images/image 19.png",
      title: "Pangatikan",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "9.  ",
      imageUrl: "images/image 19.png",
      title: "Pasirwangi",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "1.  ",
      imageUrl: "images/image 19.png",
      title: "	Peundeuy",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "2.  ",
      imageUrl: "images/image 19.png",
      title: "Selaawi",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "3.  ",
      imageUrl: "images/image 19.png",
      title: "Singajaya ",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "4.  ",
      imageUrl: "images/image 19.png",
      title: "Sucinaraja",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "detailpage"),
  Wisata(
      nomer: "5.  ",
      imageUrl: "images/image 19.png",
      title: "Sukaresmi",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "6.  ",
      imageUrl: "images/image 19.png",
      title: "Sukawening",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
  Wisata(
      nomer: "7.  ",
      imageUrl: "images/image 19.png",
      title: "Talegong",
      lokasi: "Destinasi Wisata",
      rate: "55",
      link: "link"),
];
